services:
    App\Twitter\Infrastructure\Api\AccessToken\TokenChange:
        class: 'App\Twitter\Infrastructure\Api\AccessToken\TokenChange'
        arguments:
            - '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface'
            - '@logger'

    App\Twitter\Infrastructure\Api\Accessor\OwnershipAccessor:
        class: 'App\Twitter\Infrastructure\Api\Accessor\OwnershipAccessor'
        arguments:
            - '@App\Twitter\Infrastructure\Api\Accessor'
            - '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface'
            - '@App\Twitter\Infrastructure\Api\AccessToken\TokenChange'
            - '@logger'
        calls:
            - [ 'setOwnershipBatchCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\OwnershipBatchCollectedEventRepository'] ]

    App\Twitter\Infrastructure\Api\Accessor\MemberProfileAccessor:
        class: 'App\Twitter\Infrastructure\Api\Accessor\MemberProfileAccessor'
        arguments:
            - '@App\Twitter\Infrastructure\Api\Accessor'
            - '@user_manager'
            - '@App\Twitter\Infrastructure\Api\UnavailableResourceHandler'
        calls:
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository'] ]

    App\Twitter\Domain\Api\Accessor\MemberProfileAccessorInterface:
        '@App\Twitter\Infrastructure\Api\Accessor\MemberProfileAccessor'

    App\Twitter\Infrastructure\Api\Security\Authorization\AuthorizeAccess:
        class: 'App\Twitter\Infrastructure\Api\Security\Authorization\AuthorizeAccess'
        arguments:
            - '%twitter_api.consumer_key%'
            - '%twitter_api.consumer_secret%'

    App\Twitter\Domain\Api\Security\Authorization\AuthorizeAccessInterface:
        '@App\Twitter\Infrastructure\Api\Security\Authorization\AuthorizeAccess'

    App\Twitter\Infrastructure\Api\Security\Authorization\Console\AuthorizeApplicationCommand:
        class: 'App\Twitter\Infrastructure\Api\Security\Authorization\Console\AuthorizeApplicationCommand'
        arguments:
            - !php/const 'App\Twitter\Infrastructure\Api\Security\Authorization\Console\AuthorizeApplicationCommand::COMMAND_NAME'
            - '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface'
            - '@App\Twitter\Domain\Api\Security\Authorization\AuthorizeAccessInterface'
            - '@App\Twitter\Domain\Api\Accessor\MemberProfileAccessorInterface'
            - '@App\Twitter\Domain\Membership\Repository\MemberRepositoryInterface'
            - '@logger'
        tags:
            - { name: 'console.command' }