services:
    App\Twitter\Infrastructure\Api\Accessor\FriendsListAccessor:
        class: 'App\Twitter\Infrastructure\Api\Accessor\FriendsListAccessor'
        arguments:
            - '@App\Twitter\Infrastructure\Api\Accessor'
            - '@logger'

    App\Twitter\Infrastructure\Api\Mutator\FriendshipMutator:
        class: 'App\Twitter\Infrastructure\Api\Mutator\FriendshipMutator'
        calls:
            - [ 'setApiAccessor', [ '@App\Twitter\Infrastructure\Api\Accessor' ] ]
            - [ 'setLogger', [ '@logger' ] ]
            - [ 'setMemberRepository', [ '@App\Twitter\Infrastructure\Membership\Repository\MemberRepository' ] ]
            - [ 'setMemberSubscriptionRepository', [ '@repository.member_subscription' ] ]

    App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand'
        calls:
            - [ 'setAccessor', ['@App\Twitter\Infrastructure\Api\Accessor\FriendsListAccessor'] ]
            - [ 'setRepository', ['@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository'] ]
        tags:
            - { name: 'console.command' }

    App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand'
        calls:
            - [ 'setMutator', [ '@App\Twitter\Infrastructure\Api\Mutator\FriendshipMutator' ] ]
            - [ 'setListCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository' ] ]
            - [ 'setMemberRepository', [ '@App\Twitter\Infrastructure\Membership\Repository\MemberRepository' ] ]
        tags:
            - { name: 'console.command' }

    App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand'
        arguments:
            - !php/const App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand::COMMAND_NAME
            - '@App\Twitter\Domain\Curation\Repository\OwnershipBatchCollectedEventRepositoryInterface'
            - '@logger'
        tags:
            - { name: 'console.command' }
