services:
    App\Twitter\Infrastructure\Amqp\MessageBus\PublishersListDispatcher:
        class: 'App\Twitter\Infrastructure\Amqp\MessageBus\PublishersListDispatcher'
        calls:
            - [ 'setPublishersListRepository', [ '@App\Twitter\Infrastructure\Api\Repository\PublishersListRepository' ] ]
            - [ 'setMessageBus',                [ '@messenger.default_bus' ] ]