imports:
    - { resource: config.yml }

parameters:
    main_log_level:     'debug'
    sentry_log_level:   'error'

monolog:
    channels:
        - 'development'
        - 'membership'
        - 'status'
        - 'twitter_api'
        - 'messaging'
    handlers:
        main:   "%monolog_main_logging_handler%"
