doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '13.1'
                logging: false
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            correlation_id:  App\Twitter\Infrastructure\Operation\Correlation\CorrelationIdType
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                connection: default
                mappings:
                    Api:
                        alias:      'Api'
                        is_bundle:  false
                        dir:        '%kernel.project_dir%/src/Twitter/Infrastructure/Api/Entity'
                        prefix:     'App\Twitter\Infrastructure\Api\Entity'
                        type:       annotation
                    Member:
                        alias:      'Member'
                        dir:        '%kernel.project_dir%/config/model/member'
                        is_bundle:  false
                        prefix:     App\Membership\Infrastructure\Entity
                        type:       xml
                    Membership:
                        alias:      'Membership'
                        dir:        '%kernel.project_dir%/src/Membership/Infrastructure/Entity/Legacy'
                        is_bundle:  false
                        prefix:     App\Membership\Infrastructure\Entity\Legacy
                        type:       annotation
                    NewsReviewRouting:
                        alias:      'NewsReviewRouting'
                        dir:        '%kernel.project_dir%/config/model/news-review-routing'
                        is_bundle:  false
                        prefix:     App\NewsReview\Infrastructure\Routing\Entity
                        type:       xml
                    PressMedia:
                        alias:      'PressMedia'
                        dir:        '%kernel.project_dir%/config/model/press-media'
                        is_bundle:  false
                        prefix:     App\PressMedia\Entity
                        type:       xml
                    Popularity:
                        alias:      'Popularity'
                        dir:        '%kernel.project_dir%/config/model/popularity'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\PublicationPopularity\Entity
                        type:       xml
                    Publication:
                        alias:      'Publication'
                        dir:        '%kernel.project_dir%/src/Twitter/Infrastructure/Publication/Entity'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Publication\Entity
                        type:       annotation
                    PublicationBatchCollectedEvent:
                        alias:      'PublicationBatchCollectedEvent'
                        dir:        '%kernel.project_dir%/config/model/curation'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Curation\Entity
                        type:       xml
                    PublishersList:
                        alias:      'PublishersList'
                        dir:        '%kernel.project_dir%/config/model/publication-list'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\PublishersList\Entity
                        type:       xml
