framework:
    messenger:
        failure_transport: failed

        # @see https://symfony.com/doc/current/messenger.html#middleware-for-doctrine
        buses:
            messenger.bus.default:
                middleware:
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            news_status:    '%env(MESSENGER_TRANSPORT_DSN_STATUS)%'
            news_likes:     '%env(MESSENGER_TRANSPORT_DSN_LIKES)%'
            failed:         '%env(MESSENGER_TRANSPORT_DSN_FAILURES)%'

        routing:
            # Route your messages to the transports
            'App\Twitter\Infrastructure\Amqp\Message\FetchMemberStatus': news_status
            'App\Twitter\Infrastructure\Amqp\Message\FetchMemberLikes':  news_likes
