parameters:
    weaving_the_web.quality_assurance.finder.class:              Symfony\Component\Finder\Finder
    weaving_the_web.quality_assurance.loader.class:              Symfony\Bridge\Doctrine\DataFixtures\ContainerAwareLoader
    weaving_the_web.quality_assurance.executor.class:            Doctrine\Common\DataFixtures\Executor\ORMExecutor
    weaving_the_web.quality_assurance.purger.class:              Doctrine\Common\DataFixtures\Purger\ORMPurger
    weaving_the_web.quality_assurance.string_input.class:        Symfony\Component\Console\Input\StringInput
    weaving_the_web.quality_assurance.stream_output.class:       Symfony\Component\Console\Output\StreamOutput
    weaving_the_web.quality_assurance.schema_manipulator.class:  Doctrine\ORM\Tools\SchemaTool
    weaving_the_web.quality_assurance.user.username:             User
    weaving_the_web.quality_assurance.user.password:             'WN6!e1SfH92#8zbB#nnGKlrxHr*ounQJB^sML!Rb44Cs3I!Q^n'
    weaving_the_web.quality_assurance.super.username:            Super
    weaving_the_web.quality_assurance.super.password:            'Rb44Cs3I'

services:
    weaving_the_web.quality_assurance.fixtures.executor:
        class: '%weaving_the_web.quality_assurance.executor.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@weaving_the_web.quality_assurance.fixtures.purger'
    weaving_the_web.quality_assurance.fixtures.finder:
        class: '%weaving_the_web.quality_assurance.finder.class%'
    weaving_the_web.quality_assurance.fixtures.loader:
        class: '%weaving_the_web.quality_assurance.loader.class%'
        arguments:
            - '@service_container'
    weaving_the_web.quality_assurance.fixtures.purger:
        class: '%weaving_the_web.quality_assurance.purger.class%'
    weaving_the_web.quality_assurance.fixtures.schema_manipulator:
        class: '%weaving_the_web.quality_assurance.schema_manipulator.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
    weaving_the_web.quality_assurance.fixtures.test_mysql_executor:
        class: '%weaving_the_web.quality_assurance.executor.class%'
        arguments:
            - '@doctrine.orm.test_mysql_entity_manager'
            - '@weaving_the_web.quality_assurance.fixtures.purger'
    weaving_the_web.quality_assurance.fixtures.test_mysql_schema_manipulator:
        class: '%weaving_the_web.quality_assurance.schema_manipulator.class%'
        arguments:
            - '@doctrine.orm.test_mysql_entity_manager'
