parameters:
    api_twitter_consumer_key:                                   %api_twitter_consumer_key_test%
    api_twitter_consumer_secret:                                %api_twitter_consumer_secret_test%
    api_twitter_user_secret:                                    %api_twitter_user_secret_test%
    api_twitter_user_token:                                     %api_twitter_user_token_test%

    database_charset:                                           UTF8
    database_driver:                                            pdo_mysql
    database_host:                                              %database_host_test%
    database_port:                                              %database_port_test%
    database_name:                                              %database_name_test%
    database_user:                                              %database_user_test%
    database_password:                                          %database_password_test%

    database_charset_read:                                      UTF8
    database_driver_read:                                       pdo_mysql
    database_host_read:                                         %database_host_test%
    database_port_read:                                         %database_port_test%
    database_name_read:                                         %database_name_test%
    database_user_read:                                         %database_user_test%
    database_password_read:                                     %database_password_test%

    database_charset_write:                                     UTF8
    database_driver_write:                                      pdo_mysql
    database_host_write:                                        %database_host_test%
    database_port_write:                                        %database_port_test%
    database_name_write:                                        %database_name_test%
    database_user_write:                                        %database_user_test%
    database_password_write:                                    %database_password_test%
