services:
    controller.authentication:
        class: 'App\Member\Authentication\Controller\AuthenticationController'
        properties:
            authenticator:        '@app.authenticator'

    controller.list:
        class: 'App\Aggregate\Controller\ListController'
        properties:
            allowedOrigin:                  '%allowed.origin%'
            configDirectory:                '%kernel.root_dir%/config'
            authenticationTokenRepository:  '@repository.authentication_token'
            aggregateLikesProducer:         '@old_sound_rabbit_mq.weaving_the_web_amqp.producer.aggregates_likes_producer'
            aggregateRepository:            '@repository.aggregate'
            aggregateStatusesProducer:      '@old_sound_rabbit_mq.weaving_the_web_amqp.twitter.aggregates_status_producer'
            environment:                    '%kernel.environment%'
            highlightRepository:            '@repository.highlight'
            logger:                         '@logger'
            memberRepository:               '@user_manager'
            router:                         '@router'
            redisCache:                     '@app.cache.redis'
            timelyStatusRepository:         '@repository.timely_status'
            tokenRepository:                '@weaving_the_web_api.repository.token'
            httpAuthenticator:              '@app.security.http_authenticator'

    controller.logged_in_member:
        class: 'App\Member\Controller\LoggedInMemberController'
        properties:
            logger:                        '@logger'
            authenticationTokenRepository: '@repository.authentication_token'
            allowedOrigin:                 '%allowed.origin%'
            environment:                   '%kernel.environment%'

    controller.aggregate:
        class: 'App\Aggregate\Controller\AggregateController'
        properties:
            aggregateRepository: '@repository.aggregate'
            allowedOrigin:       '%allowed.origin%'
            environment:         '%kernel.environment%'
            redisCache:          '@app.cache.redis'

    controller.keyword:
        class: 'App\Aggregate\Controller\KeywordController'
        properties:
            keywordRepository: '@repository.keyword'
            allowedOrigin:     '%allowed.origin%'
            environment:       '%kernel.environment%'
            redisCache:        '@app.cache.redis'

    controller.subscription:
        class: 'App\Aggregate\Controller\SubscriptionController'
        properties:
            allowedOrigin:                  '%allowed.origin%'
            environment:                    '%kernel.environment%'
            httpAuthenticator:              '@app.security.http_authenticator'
            memberSubscriptionRepository:   '@repository.member_subscription'
            redisCache:                     '@app.cache.redis'

    controller.member:
        class: 'App\Member\Controller\MemberController'
        properties:
            allowedOrigin:          '%allowed.origin%'
            environment:            '%kernel.environment%'
            httpAuthenticator:      '@app.security.http_authenticator'
            memberProfileAccessor:  '@accessor.member_profile'
            logger:                 '@monolog.logger.twitter_api'
