version: '3'
services:

    # https://doc.traefik.io/traefik/getting-started/quick-start/
    reverse-proxy:
        image: traefik:v2.3
        command: --providers.docker --api.insecure=true
        ports:
            # The HTTP port
            - "80:80"
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock

    web:
        build: ./apache
        networks:
            - devobs-network
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - ../containers/apache/templates:/templates
            - ../containers/apache/tasks:/tasks
            - ../containers/apache/templates/20-no-xdebug.ini.dist:/usr/local/etc/php/conf.d/20-xdebug.ini
            - ../containers/apache/templates/blackfire/zz-blackfire.ini:/usr/local/etc/php/conf.d/zz-blackfire.ini
            - ../containers/apache/templates/blackfire/.blackfire.ini:/root/.blackfire.ini
            - ../containers/apache/templates/blackfire/agent:/etc/blackfire/agent
            - ../../:/var/www/api
        depends_on:
            - cache
            - worker

    worker:
        build: ./php
        networks:
            devobs-network:
                aliases:
                    - worker
        volumes:
            - ../containers/php/templates/20-no-xdebug.ini.dist:/usr/local/etc/php/conf.d/20-xdebug.ini
            - ../../:/var/www/api
        depends_on:
            - messenger

    database:
        build: ./postgres
        networks:
            devobs-network:
                aliases:
                    - database
        restart: always
        env_file:
            - ../../.env.local
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - ../volumes/postgres:/var/lib/postgresql/data

    messenger:
        build: ./rabbitmq
        expose:
            - "5672"
        networks:
            devobs-network:
                aliases:
                    - messenger
        restart: always
        env_file:
            - ../../.env.local
        volumes:
            - ../volumes/rabbitmq:/var/lib/rabbitmq

    cache:
        image: redis
        command:
            redis-server --appendonly yes
        expose:
            - "6379"
        restart: always
        networks:
            devobs-network:
                aliases:
                    - cache
        volumes:
            - ../volumes/redis:/data

networks:
    devobs-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.169.193.0/28
